### ISSUE TITLE
-dsft: add EXIF timestamp if missing

### ISSUE THREAD

**Issue by richlv** [Matthias-Wandel/jhead#10]
```
> jhead -dsft LJLZ4932.JPG
File 'LJLZ4932.JPG' contains no Exif timestamp to change
```

If possible, it would be great if the `-dsft` flag added the EXIF timestamp field (EXIF itself exists in this case).

**Comment by Matthias-Wandel** [comment]
Exif is a write-only file system.  Because the structure can contain 
undocumented other parts, it's not safe to modify and existing exif 
header.
There is however an option to make a new exif header (which deletes the 
old one if there is one)

------ Original Message ------

**Comment by richlv** [comment]
Oh, I see. Would it perhaps be possible to have a flag to copy existing data, with a big warning in the usage docs?

**Comment by Matthias-Wandel** [comment]
Too much work for a feature almost no one would use

**Comment by Matthias-Wandel** [comment]
I should add, the feature to make an existing exif header only makes a minimal exif header, and it does copy existing data for that.
