### ISSUE TITLE
-ds does not accept any input data

### ISSUE THREAD

**Issue by richlv** [Matthias-Wandel/jhead#11]
Sorry if I'm misunderstanding the flag - but all attempts to set date with the `-ds` flag have failed so far.

```
> jhead -ds "2000" LJLZ4932.JPG

Error : Date must be in format YYYY, YYYY:MM, or YYYY:MM:DD
> jhead -ds "2000:01" LJLZ4932.JPG

Error : Date must be in format YYYY, YYYY:MM, or YYYY:MM:DD
> jhead -ds "2000:01:01" LJLZ4932.JPG

Error : Date must be in format YYYY, YYYY:MM, or YYYY:MM:DD
```

**Comment by Matthias-Wandel** [comment]
Oops, I guess it used to do that.  I'll have to fix that.

------ Original Message ------

**Comment by Matthias-Wandel** [comment]
On review, it works exactly as documented.  No space between -ds and first digit of date.
