### ISSUE TITLE
autorot does not adjust face tags

### ISSUE THREAD

**Issue by mblythe86** [Matthias-Wandel/jhead#13]
When I use the `-autorot` option on an image with face tags, it doesn't adjust the face tag coordinates accordingly.  As a result, the tags are no longer located on their respective faces.

It looks like the face tag metadata is stored in the XMP section, which jhead doesn't seem to support.  If that's the case, please feel free to reject.

However, if jhead does support updating XMP metadata, I'm happy to provide example files.

**Comment by Matthias-Wandel** [comment]
It only displays and deletes xmp.

**Comment by mblythe86** [comment]
Fair enough, thanks.  Closing.
