### ISSUE TITLE
Invalid SOS parameters for sequential JPEG

### ISSUE THREAD

**Issue by vomov** [Matthias-Wandel/jhead#18]
While running the following:
`jhead -autorot */*.jpg -se`
I get:
`Invalid SOS parameters for sequential JPEG`
on some files.

The files in question appear to be taken with the 'selfie'-camera of a Samsung phone.

Expected behavior would be to show the error, but continue with the rest of the operation.

**Comment by Matthias-Wandel** [comment]
That message is caused by an invalid parameter in the image.  Not all cameras encode all fields correctly.

**Comment by Matthias-Wandel** [comment]
I should add, that message comes from jpegtran, not jhead.  Still caused by an invalid SOS parameter in the image.
