### ISSUE TITLE
Fix parallel builds

### ISSUE THREAD

**Issue by joachim-reichel** [Matthias-Wandel/jhead#38]
Since OBJ no longer defaults to the current working directory, there is now a race condition in parallel builds. This can be fixed by making the "objdir" target a precondition of the rules for the object files, as in the following patch:
[fix_parallel_build.txt](https://github.com/Matthias-Wandel/jhead/files/6566494/fix_parallel_build.txt)

**Comment by Matthias-Wandel** [comment]
If you would like me to integrate this into my jhead project, please 
send a pull request to my jhead project.

------ Original Message ------
From: "Joachim Reichel" ***@***.***>
To: "Matthias-Wandel/jhead" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 2021-05-30 1:17:07 PM
Subject: [Matthias-Wandel/jhead] Fix parallel builds (#38)

**Comment by Matthias-Wandel** [comment]
Integrated in change bf810295d1719893ae282c4f490f3e62cf59a30f
