### ISSUE TITLE
make do not work on Windows without the "obj" folder

### ISSUE THREAD

**Issue by masya-chel** [Matthias-Wandel/jhead#39]
I have installed Microsoft Visual Studio 2017 Build Tools (on Windows 7 x64).
When trying to execute make, an errors is displayed in the console.
If I manually create the "obj" folder in the project folder, then when I run make, the project is compiled successfully.

As a temporary solution, I added a folder creation command to the file "make.bat":

```
mkdir obj
nmake -f makefile-win32
```

Now, when I run make, the project is successfully building.

**Comment by Matthias-Wandel** [comment]
Fixed with e9d28f30a85396b7ff7cd64bc35bc33b6e5435cf
