### ISSUE TITLE
jpegtran not found if only in local dir

### ISSUE THREAD

**Issue by tsmgeek** [Matthias-Wandel/jhead#41]
Found a minor issue in latest.

We keep our tools in a single directly and not included in the PATH list, this causes a problem as the app will not find jpegtran when its in a folder other than that in the include PATH.

Could we have either an argument that allows specifying the path to jpegtran?

**Comment by Matthias-Wandel** [comment]
Just add the local dir to your path

**Comment by tsmgeek** [comment]
I could do but I really do not want that directory to be on the include PATH hence why it would be good to be able to override it or look in the same directory where jpegtran exists.

**Comment by Matthias-Wandel** [comment]
Well, I really don't want to add an option that only one person will 
use, so it would be a good idea to just solve the problem with the path 
on your end, or add a softlink somewhere on your path to the copy in 
your local directory.

The beauty of that is that you, who wants this, can solve it, and me, 
who is not interested in this feature, don't have to pollute the code 
base with this feature.

------ Original Message ------
From: "Ricardo" ***@***.***>
To: "Matthias-Wandel/jhead" ***@***.***>
Cc: "Matthias Wandel" ***@***.***>; "Comment" 
***@***.***>
Sent: 2021-08-18 1:46:33 PM
Subject: Re: [Matthias-Wandel/jhead] jpegtran not found if only in local 
dir (#41)
