### ISSUE TITLE
I assume this is a typo?

### ISSUE THREAD

**Issue by G2G2G2G** [Matthias-Wandel/jhead#44]
ROTATION TAG MANIPULATION:
  -autorot   Invoke jpegtran to rotate images according to Exif orientation tag
             **anc** clear Exif orientation tag

supposed to be and? pretty sure.

**Comment by Matthias-Wandel** [comment]
Please tell me where this is from.  I can't find it in the code.

------ Original Message ------
From: "G2G2G2G" ***@***.***>
To: "Matthias-Wandel/jhead" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 2021-09-14 3:16:34 PM
Subject: [Matthias-Wandel/jhead] I assume this is a typo? (#44)

**Comment by G2G2G2G** [comment]
I couldn't find it either, it's from when I type `jhead -h`

Installed via `pacman -S jhead`  did they alter the help code?

**Comment by Matthias-Wandel** [comment]
Fixed a while ago in 8384c6fd2ebfb8eb8bd9661
