### ISSUE TITLE
heic

### ISSUE THREAD

**Issue by mailinglists35** [Matthias-Wandel/jhead#47]
would be useful to be able to manipulate apple's heic format

**Comment by wodokm** [comment]
I fully understand ;-) My request would be to just grab the Exif from HEIC, to be able to rename them. Don't need to modify/write back the HEIC. Do you think this would easily be possible, like just searching for "Exif" in the file and then trigger the Exif-parser, or is that all bound more to JPEG? I'm not asking you to do it, I would maybe myself try to get it hacked into and contribute.
Cheers, Martin

**Comment by Matthias-Wandel** [comment]
This requires parsing the HEIC file, which requires knowledge of this type of file, which I don't have time to aquire.  it will also lead to further issues getting reported if it only supports reading the exif.  So best to just leave it at not supporting HEIC.
