### ISSUE TITLE
jhead -n is not atomic and can permanently erase files

### ISSUE THREAD

**Issue by vn971** [Matthias-Wandel/jhead#52]
`jhead -n` seems to be not atomic and can potentially erase files.

### Steps to reproduce:
* create 10 jpg copies named 0.jpg, 1.jpg, 2.jpg, 3.jpg, ...
* create a script:
```
jhead -ft -n 0.jpg &
jhead -ft -n 1.jpg &
jhead -ft -n 2.jpg &
jhead -ft -n 3.jpg &
jhead -ft -n 4.jpg &
jhead -ft -n 5.jpg &
jhead -ft -n 6.jpg &
jhead -ft -n 7.jpg &
jhead -ft -n 8.jpg &
jhead -ft -n 9.jpg &
```
This script runs multiple `jhead` instances in parallel and asks it to rename all files to the same timestamp
* run the script

### Expected at this point:
Get multiple files named like xxxxx.jpg, xxxxx0.jpg, xxxxx1.jpg, ... xxxxx8.jpg  (in total 10 files)

### Observed behavior
Sometimes the jhead's run just fine and no bug is observed. Sometimes, however, you would see that the total number of files has reduced, one of the files effectively got erased.

### Understanding
I'm not sure where the bug originates from exactly. Overall it's due to the non-atomicity of creating the new file apparently. I was originally expecting a TOCTOU problem with checking that a rename is possible first, and then renaming (at which point the file can already exists and it'd be an erasing move).

However, it seems to be a bit trickier here. 
This line is potentially the offender: https://github.com/Matthias-Wandel/jhead/blob/master/jhead.c#L540

Depending on how it's written, it can be either safe against TOCTOU or not. (If a file is opened with the right flags, it *can* be create-or-return-error, so a correct solution in C is generally possible.)

However, I couldn't find where `find_handle` comes from. (I'm not very good at C sorry.)

Thoughts? Any ideas how to fix that?

### Version
Version `v3.06 Matthias Wandel, Oct 5 2020` as reported by `jhead -h`, or `3.06.0.1` as reported by pacman (ArchLinux).

**Comment by Matthias-Wandel** [comment]
Ok, then don’t do that.

**Comment by Matthias-Wandel** [comment]
This is a corner case that you need to go out of your way to hit, and you need contrived circumstances to do it - having identical files processed identically at the same time.

However, if you have a simple fix for that, feel free to submit a patch for it.

I don't consider this to be a significant issue, so closing this one.
