### ISSUE TITLE
Jhead stack-buffer-overflow by misuse of the option "-te"

### ISSUE THREAD

**Issue by randomssr** [Matthias-Wandel/jhead#55]
When the option "-te" argument contains "&i" and there are many string before "&i", the stack buffer will overflow.

Jhead/jhead.c
Line 502-507
```
Subst = strstr(NamePattern, "&i");
if (Subst){
    strncpy(OutFileName, NamePattern, Subst-NamePattern);
    OutFileName[Subst-NamePattern] = 0;
    strncat(OutFileName, OrigName, PATH_MAX);
    strncat(OutFileName, Subst+2, PATH_MAX);
```
In `RelativeName()`,the argument of "-te" is passed to the `RelativeName()` as `NamePattern`. However, if the argument contains `"&i"` and the string length before `"&i"` exceeds the length of OutFileName, then the third parameter of `strncpy` will exceed the length of OutFileName. As a result, the buffer will overflow.

### Test Environment
Ubuntu 20.04, 64 bit
Jhead (master, [0e98605](https://github.com/Matthias-Wandel/jhead/commit/0e98605d0a08bc692b87ca878bb4dc7bdfc12471))

### How to trigger
1. Compile the program with AddressSanitizer
2. Run command ``` $ ./jhead -te `python -c "print('a'*30000+'&icccccc')"` 123 ```

#### ASAN report
```
$ ./jhead -te `python -c "print('a'*30000+'&icccccc')"` 123
=================================================================
==18113==ERROR: AddressSanitizer: strncpy-param-overlap: memory ranges [0x7ffdd65c31c0,0x7ffdd65ca6f0) and [0x7ffdd65c8e2d, 0x7ffdd65d035d) overlap
    #0 0x7fed4364d546 in __interceptor_strncpy ../../../../src/libsanitizer/asan/asan_interceptors.cpp:483
    #1 0x55a558d77cbb in strncpy /usr/include/x86_64-linux-gnu/bits/string_fortified.h:106
    #2 0x55a558d77cbb in RelativeName jhead.c:505
    #3 0x55a558d784b6 in ProcessFile jhead.c:901
    #4 0x55a558d76e8b in main jhead.c:1772
    #5 0x7fed432d6082 in __libc_start_main ../csu/libc-start.c:308
    #6 0x55a558d77b6d in _start (/home/ubuntu20/bug_report/jhead/crash/jhead+0xcb6d)

Address 0x7ffdd65c31c0 is located in stack of thread T0
Address 0x7ffdd65c8e2d is located in stack of thread T0
SUMMARY: AddressSanitizer: strncpy-param-overlap ../../../../src/libsanitizer/asan/asan_interceptors.cpp:483 in __interceptor_strncpy
==18113==ABORTING
```

**Comment by Matthias-Wandel** [comment]
Fixed by e6294430d382fc49de41299b263e291b057890f7
