### ISSUE TITLE
[Help document bug] For jhead, the help document misses the "proc" option

### ISSUE THREAD

**Issue by ccccmd** [Matthias-Wandel/jhead#56]
The "--help" option of jhead misses the option "proc" for version 3.06.0.1.

+ For the option "proc", the following code appears during option parsing and modifies the ProcessOnly and maybe print some error information in jhead.c:1684-1687 for version 3.06.0.1.

```
            sscanf(argv[++argn], "%d", &ProcessOnly);
            if (ProcessOnly < 0 || ProcessOnly > 2){
                ErrFatal("-proc must be followed by a number 0-2");
            }
```

But they do not appear in the document provided by "-h".

It may prevent users from using the relevant function.

**Comment by Matthias-Wandel** [comment]
That was probably the idea.
Had to look at the code to figure to figure out what it even does, and 
I'm pretty sure no one else would use that.

------ Original Message ------
From: "ccccmd" ***@***.***>
To: "Matthias-Wandel/jhead" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 9/30/2022 3:59:14 AM
Subject: [Matthias-Wandel/jhead] [Help document bug] For jhead, the help 
document misses the "proc" option (Issue #56)
