### ISSUE TITLE
Aborted in Jhead at jpgfile.c:354

### ISSUE THREAD

**Issue by Ngiong** [Matthias-Wandel/jhead#6]
Hello,
We are currently working on a new fuzz testing feature, and we found a crash in jhead.

**Step to Reproduce**
We used `CFLAGS="-g -O0" make` to compile the jhead, and run it with:
```
./jhead -dsft -di <attached_file> -exonly
```
Attachment: [poc_0005.txt](https://github.com/Matthias-Wandel/jhead/files/5420175/poc_0005.txt)

**Environment**
 - OS: Ubuntu 18.04.4 LTS
 - Compiler: gcc 7.5.0
 - jhead version: 3.04 (https://www.sentex.ca/~mwandel/jhead/jhead-3.04.tar.gz)

**Additional context**
Here's the stack trace: [stack_trace_0005.txt](https://github.com/Matthias-Wandel/jhead/files/5420347/stack_trace_0005.txt)

```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff76868b1 in __GI_abort () at abort.c:79
#2  0x00007ffff76cf907 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff77fcdfa "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff76d697a in malloc_printerr (str=str@entry=0x7ffff77fb000 "free(): invalid size") at malloc.c:5350
#4  0x00007ffff76dde9c in _int_free (have_lock=0, p=0x617640, av=0x7ffff7a31c40 <main_arena>) at malloc.c:4161
#5  __GI___libc_free (mem=0x617650) at malloc.c:3124
#6  0x0000000000404680 in DiscardData () at jpgfile.c:354
#7  0x000000000040388f in main (argc=<optimized out>, argv=<optimized out>) at jhead.c:692
```

Thank you.

**Comment by Matthias-Wandel** [comment]
Fixed by change df124a448eebf35db8bb52e7716a08f1d02d720b on 
https://github.com/Matthias-Wandel/jhead

------ Original Message ------
