### ISSUE TITLE
jhead -ce: "Editor failed to launch: Success"

### ISSUE THREAD

**Issue by jwilk** [Matthias-Wandel/jhead#61]
```console
$ EDITOR=blah jhead -ce tests/comments.jpg

Nonfatal Error : 'tests/comments.jpg' Illegally sized Exif subdirectory (4 entries)
sh: 1: blah: not found
Editor failed to launch: Success
```

No, I'm pretty sure it was not a success. :)
Please fix the error message.

**Comment by Matthias-Wandel** [comment]
I'm just printing the error code i got from linux.
But if you read the output, it's pretty clear that it didn't work.
If you deliberately try to mess it up and then the message is not as clear as it could be, that is your problem, not mine.
