### ISSUE TITLE
large hour adjustment off by 1 year

### ISSUE THREAD

**Issue by airdrummer** [Matthias-Wandel/jhead#63]
adjusting IMG_2722.JPG from 16/10/2022 11:10:59 to 15/09/2022 11:10:31 
>  jhead -ta-9504:00:28 -ft IMG_2722.JPG
results in 15/09/2021 11:10:31
i dont use -da becaue i need the delta time value for other images needing the same offset

**Comment by airdrummer** [comment]
typo in description: manipulate not manipupate (unless u r modifying an insect;-)

**Comment by airdrummer** [comment]
using brew's jhead: v3.06 Matthias Wandel, Oct 5 2020
i'll compile & test local clone...

**Comment by Matthias-Wandel** [comment]
Some day I will have time to look at this.

------ Original Message ------
From: "tom wible" ***@***.***>
To: "Matthias-Wandel/jhead" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 10/20/2022 11:27:36 AM
Subject: [Matthias-Wandel/jhead] large hour adjustment off by 1 year 
(Issue #63)

**Comment by airdrummer** [comment]
nevermind...applescript dates screwed me over:-{ code worked when i wrote it in previous macos versions:-\
