### ISSUE TITLE
add Ubuntu installation methode

### ISSUE THREAD

**Issue by hirntot** [Matthias-Wandel/jhead#69]
running linuxmint 21 here. 

just after compiling the source, I tried to type "apt install jhead" and surprisingly it just installed.
so, please add this install option to your readme. might save some trouble to others.
btw: I love your licence note.
thanks and cheers.

![Bildschirmfoto vom 2023-03-20 05-53-34](https://user-images.githubusercontent.com/5942208/226250039-3037c2ab-5d31-4492-a094-d00dc28c1578.png)

**Comment by Matthias-Wandel** [comment]
Yes, you can install the not latest version using apt-install.  But if the latest version says that you can install it that way, well, that is actually not true.

**Comment by hirntot** [comment]
Well, I didn't ask whether it's possible to install jhead via apt, but I wanted to suggest that you mention this possibility in your readme to help other users installing jhead easily via command line.✌️

**Comment by Matthias-Wandel** [comment]
Ok, good point, updated readme, change a0eed69daa6ad4b824eb81fb6e3be95de3f783c2
