### ISSUE TITLE
There is a command injection vulnerability when the "-ce" option is enable

### ISSUE THREAD

**Issue by W4terf1re** [Matthias-Wandel/jhead#70]
In jhead.c, the content of the environment variable "EDITOR" will become a part of "QuotedPath" which is the argument for the system function.
```{
        char * Editor;
        Editor = getenv("EDITOR");
        if (Editor == NULL){
#ifdef _WIN32
            Editor = "notepad";
#else
            Editor = "vi";
#endif
        }
        if (strlen(Editor) > PATH_MAX) ErrFatal("env too long");

        // Disallow characters in the editor or filename that could be used to execute arbitrary
        // shell commands with system() below.
        if (strpbrk(TempFileName, "\";'&|`$")) {
            ErrFatal("Filename has invalid characters");
        }
        if (strpbrk(Editor, "\";'&|`$")) {
            ErrFatal("Editor has invalid characters");
        }

        sprintf(QuotedPath, "%s \"%s\"",Editor, TempFileName);
        a = system(QuotedPath);
    }
```
Although the program filters some characters, the attacker can cause arbitrary command execution or privilege escalation by setting the environment variable "EDITOR".
Here is an exmaple:
```
$ export EDITOR="wget https://github.com/Matthias-Wandel/jhead/archive/refs/tags/3.06.0.1.zip"
$ ./jhead -ce ./a.jpeg
```
To mitigate the problem, it is better to filter more special characters like space or colon.

**Comment by Matthias-Wandel** [comment]
If the user has that much control over the system, why would they just not take over the system by typing regular commands into it instead of jumping through hopos to do it through jhead.  This "issue" makes no sense.

**Comment by W4terf1re** [comment]
In some situations the vulnerability could be utilized. For example, some systems provide a restricted shell to interact with, and the shell only provides a limited number of commands. It is possible for an attacker to escape from the restricted shell and execute the commands which are originally not allowed.
