### ISSUE TITLE
Bug in jhead: Unaddressable Access

### ISSUE THREAD

**Issue by leocstone** [Matthias-Wandel/jhead#75]
Hello,

I recently discovered an input which causes jhead.exe to read an invalid pointer.

The input is attached - tested under Windows 10 with the following command line:
jhead.exe unaddressable_access
[unaddressable_access.zip](https://github.com/Matthias-Wandel/jhead/files/11639087/unaddressable_access.zip)

**Comment by Matthias-Wandel** [comment]
what did you compile it with?
I just tested it under linux, and there is no error.

**Comment by leocstone** [comment]
I compiled with your make.bat using MSVC 2019 command line tools.
Try running under Valgrind - I'm not sure if the bug always causes a crash or exception.

**Comment by leocstone** [comment]
Assuming you're on Ubuntu or similar: `sudo apt install valgrind`
To run with Valgrind, just put it before the command line: `valgrind ./jhead unaddressable_access`

**Comment by Matthias-Wandel** [comment]
Just tried that on raspiberry pi OS.
I get a ton of warnings.

I also get a ton of warnings if I just run:
      valgrind echo "hi"

So this is not exactly useful.

------ Original Message ------
From: "Leo Stone" ***@***.***>
To: "Matthias-Wandel/jhead" ***@***.***>
Cc: "Matthias Wandel" ***@***.***>; "Comment" 
***@***.***>
Sent: 2023-06-06 3:19:09 PM
Subject: Re: [Matthias-Wandel/jhead] Bug in jhead: Unaddressable Access 
(Issue #75)

**Comment by leocstone** [comment]
Interesting - when I run with Dr. Memory on Windows 10, I get the following output:
```
~~Dr.M~~
~~Dr.M~~ Error #1: UNADDRESSABLE ACCESS beyond heap bounds: reading 0x01008c66-0x01008c70 10 byte(s) within 0x01008c60-0x01008c70
~~Dr.M~~ # 0 jhead.exe!?                      +0x0      (0x0045cf2a <jhead.exe+0x2cf2a>)
~~Dr.M~~ # 1 jhead.exe!?                      +0x0      (0x00446823 <jhead.exe+0x16823>)
~~Dr.M~~ # 2 jhead.exe!?                      +0x0      (0x004465aa <jhead.exe+0x165aa>)
~~Dr.M~~ # 3 jhead.exe!?                      +0x0      (0x00446425 <jhead.exe+0x16425>)
~~Dr.M~~ # 4 jhead.exe!?                      +0x0      (0x00446372 <jhead.exe+0x16372>)
~~Dr.M~~ # 5 jhead.exe!?                      +0x0      (0x004321f1 <jhead.exe+0x21f1>)
~~Dr.M~~ # 6 jhead.exe!?                      +0x0      (0x00433b3e <jhead.exe+0x3b3e>)
~~Dr.M~~ # 7 jhead.exe!?                      +0x0      (0x004384ee <jhead.exe+0x84ee>)
~~Dr.M~~ # 8 KERNEL32.dll!BaseThreadInitThunk
~~Dr.M~~ Note: @0:00:00.738 in thread 2600
~~Dr.M~~ Note: refers to 0 byte(s) beyond last valid byte in prior malloc
~~Dr.M~~ Note: prev lower malloc:  0x01008c00-0x01008c66
~~Dr.M~~ Note: instruction: pcmpistri %xmm0 (%edx) $0x41 -> %ecx
```
However, it doesn't seem like the bug reproduces on Linux - I don't see any error output from Valgrind when running with the same command line.

**Comment by Matthias-Wandel** [comment]
Ok, tried it with dr memory

But it just tells me there was accesses beyond malloc, not at all where 
that was in the code, even with a debug build.

I'm afraid this is not worth my time trying to chase down.

------ Original Message ------
From: "Leo Stone" ***@***.***>
To: "Matthias-Wandel/jhead" ***@***.***>
Cc: "Matthias Wandel" ***@***.***>; "Comment" 
***@***.***>
Sent: 2023-06-06 4:12:05 PM
Subject: Re: [Matthias-Wandel/jhead] Bug in jhead: Unaddressable Access 
(Issue #75)

**Comment by leocstone** [comment]
Fair enough, just wanted to do my due diligence by reporting to you.
